# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed3ba427a9b5ceae55fe940e1fc72d6756b0d3f348d3ff453cb23fc13834c355d29d44aef89b0549fbb500db4a0baf74f6e5436e0f238d7fea652990846f755

test:
  secret_key_base: af43edd7d71b7917be03ddc974ae93b9a2c2abcfd32643548576c209e570320b7aa10253fe3b6b10084484b3421dadbf52d205b71a974269b01786e4b8b06a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
